### ISSUE TITLE
Not wok with ru?!

### ISSUE THREAD

**Issue by qawsed55** [conveniencable/redmine_excel_connector#3]
I press LOAD, then try to change values and it write error. If I just change date - there is error.
May be trouble with locales?

And, date not importing correctly

![image](https://user-images.githubusercontent.com/16443881/226099261-ef8d4ca9-164a-436f-84ec-950b5432d180.png)

**Comment by conveniencable** [comment]
For the dropdown in excel, the validation source are split by "," in default which is for English and Chinese. You can change it to other character in Setting -> Validation Source Spliter.
