### ISSUE TITLE
Blank Page showing while clicking on open in Excel

### ISSUE THREAD

**Issue by meetdileep** [conveniencable/redmine_excel_connector#4]
Hello,

I have just installed Excel connector in my system. After applying setting and trying to open it is showing blank pages. Picture attached for your understanding. can you please help me over this issue.

![Excel connector open](https://github.com/conveniencable/redmine_excel_connector/assets/3448227/69de4a2d-8a3a-4afa-bb75-d3a1ebfcf110)
![Excelconnector setting](https://github.com/conveniencable/redmine_excel_connector/assets/3448227/b1ec883d-3875-4cc4-bebe-53ca4cbb612b)

Thanks in advance,
Dileep

**Comment by meetdileep** [comment]
Also to add further there is another issue. Excel is also hanging. Please reply as this plugin is very useful for us.

**Comment by meetdileep** [comment]
Thanks. It started working. Could you please let us know whether this plugin is paid plugin or free plugin

**Comment by conveniencable** [comment]
> Thanks. It started working. Could you please let us know whether this plugin is paid plugin or free plugin

It need to be paied after a month.
